trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.14.6'

stages:

# =========================
# STAGE 1 - VALIDATE
# =========================

- stage: Validate
  displayName: Terraform Validation

  jobs:
  - job: TerraformValidate

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(terraformVersion)

    - script: |
        terraform --version
      displayName: Check Terraform Version

    - script: |
        terraform init -backend=false
      displayName: Terraform Init

    - script: |
        terraform validate
      displayName: Terraform Validate


# =========================
# STAGE 2 - SECURITY SCAN
# =========================

- stage: SecurityScan
  displayName: Security Scanning

  dependsOn: Validate

  jobs:
  - job: Security

    steps:

    - checkout: self

    - script: |
        pip install checkov
      displayName: Install Checkov

    - script: |
        checkov -d .
      displayName: Checkov Scan

    - script: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      displayName: Install Trivy

    - script: |
        ./bin/trivy config .
      displayName: Trivy IaC Scan


# =========================
# STAGE 3 - TERRAFORM PLAN
# =========================

- stage: Plan
  displayName: Terraform Plan

  dependsOn: SecurityScan

  jobs:
  - job: TerraformPlan

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(terraformVersion)

    - script: |
        terraform init
      displayName: Terraform Init

    - script: |
        terraform plan -out=tfplan
      displayName: Terraform Plan

    - publish: tfplan
      artifact: terraform-plan
      displayName: Publish Terraform Plan


# =========================
# STAGE 4 - APPLY
# =========================

- stage: Apply
  displayName: Terraform Apply

  dependsOn: Plan

  condition: succeeded()

  jobs:

  - deployment: TerraformApply
    displayName: Apply Infrastructure

    environment: production

    strategy:
      runOnce:

        deploy:

          steps:

          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: $(terraformVersion)

          - script: |
              terraform init
            displayName: Terraform Init

          - download: current
            artifact: terraform-plan

          - script: |
              terraform apply -auto-approve terraform-plan/tfplan
            displayName: Terraform Apply